# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hamsign < Formula
  desc "CLI tools for amateur radio digital signing and certificate management"
  homepage "https://github.com/radiolabme/hamsign"
  version "0.1.4"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.4/hamsign_0.1.4_darwin_x86_64.tar.gz"
      sha256 "86040f7bc6e293126972da66b77c95cde5cf3713cb0cb7b168c9cba63b08bbf6"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.4/hamsign_0.1.4_darwin_aarch64.tar.gz"
      sha256 "488a33ef01facec310541237f5d76f3f79c2d298e857919dc3ecdbbc8511cf9f"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.4/hamsign_0.1.4_linux_x86_64.tar.gz"
      sha256 "fb22e26e213406bbe4783b221587e595f6ecd5b5408f0c3c522ad127c6e7bc0e"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.4/hamsign_0.1.4_linux_armv6.tar.gz"
      sha256 "f8d2ebd9dce1d842876479983d5b53bc1e85a09c409c4b2eb16c09b50c20e37c"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.4/hamsign_0.1.4_linux_aarch64.tar.gz"
      sha256 "b528b2cd2ac17d77fa7f19cf732d9a0d4b66984e9ecf26614f1cc3eb9423992d"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  test do
    system "#{bin}/loadcert", "--help"
  end
end
