# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hamsign < Formula
  desc "CLI tools for amateur radio digital signing and certificate management"
  homepage "https://github.com/radiolabme/hamsign"
  version "0.1.3"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.3/hamsign_0.1.3_darwin_x86_64.tar.gz"
      sha256 "b3d4218264596e0f135d7256ef02872443e11046a2357a0a847d5081f9eb896d"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.3/hamsign_0.1.3_darwin_aarch64.tar.gz"
      sha256 "700f6dc71b5094798b423ec759ace83bc9a9681b16c65a999905c86132e6a527"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.3/hamsign_0.1.3_linux_x86_64.tar.gz"
      sha256 "a13437369aff2a5cd098694cb8219261360919fb7ad7ccdd81e479c4a77e013a"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.3/hamsign_0.1.3_linux_armv6.tar.gz"
      sha256 "fb047db89759ed847a63e338fa25060a1d7d12ad3908f2d6b70a2e59535506b6"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.3/hamsign_0.1.3_linux_aarch64.tar.gz"
      sha256 "6d27b4addb92dec926ea0f9d7f6c3d097f6af78b1fe4bdeafac8865394f7cd0f"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  test do
    system "#{bin}/loadcert", "--help"
  end
end
