# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
# Formula synced from radiolabme/hamsign
class Hamsign < Formula
  desc "CLI tools for amateur radio digital signing and certificate management"
  homepage "https://github.com/radiolabme/hamsign"
  version "0.1.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.2/hamsign_0.1.2_darwin_x86_64.tar.gz"
      sha256 "6dae6fc0cfd83660bef5a252b1ec999fe03075e2fca5f3bf3c3658fa9eba5694"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.2/hamsign_0.1.2_darwin_aarch64.tar.gz"
      sha256 "1270f552cf6b9c8f38914c821f294eecf370a18bfc236d2682cce70c648c154e"

      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.2/hamsign_0.1.2_linux_x86_64.tar.gz"
      sha256 "5c161a2b17bb6759a11d011e37b6176baf689d9da4573bbfaa29b7c11664572d"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.2/hamsign_0.1.2_linux_armv6.tar.gz"
      sha256 "11c2fb77a678f3c0112da9a76fe611e5fa1386b739dc3a2e7d383e83bc2d7afa"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/radiolabme/hamsign/releases/download/v0.1.2/hamsign_0.1.2_linux_aarch64.tar.gz"
      sha256 "152f71fc7fd19571b698f4f14da91945048d4216971a0136e9454f435b8b13a2"
      def install
        bin.install "loadcert"
        bin.install "signdata"
        bin.install "verifycert"
      end
    end
  end

  test do
    system "#{bin}/loadcert", "--help"
  end
end
